name: commonlibs-bukkit
version: ${git.commit.id.abbrev}
main: com.solexgames.lib.commons.CommonLibsBukkit

author: SolexGames
website: https://www.solexgames.com

depend: [ProtocolLib]
loadbefore: [Neon]
